// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSQA1WaIF5O51fKBtCGXqKixMv0R49adc',
    appId: '1:950025849653:web:c9456d5a8895d41c3c1a7c',
    messagingSenderId: '950025849653',
    projectId: 'finalproject2059',
    authDomain: 'finalproject2059.firebaseapp.com',
    storageBucket: 'finalproject2059.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2v7yc-I7-O2Si_RVY5MJZ4nCy8PLHAiI',
    appId: '1:950025849653:android:5fec59c2b11f1bf33c1a7c',
    messagingSenderId: '950025849653',
    projectId: 'finalproject2059',
    storageBucket: 'finalproject2059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzsDU1qvatjwgRxBczdCYiDujQIcpPDUc',
    appId: '1:950025849653:ios:2b80ec409c9bf72d3c1a7c',
    messagingSenderId: '950025849653',
    projectId: 'finalproject2059',
    storageBucket: 'finalproject2059.appspot.com',
    iosBundleId: 'com.example.reserveVol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzsDU1qvatjwgRxBczdCYiDujQIcpPDUc',
    appId: '1:950025849653:ios:71cddddef323831d3c1a7c',
    messagingSenderId: '950025849653',
    projectId: 'finalproject2059',
    storageBucket: 'finalproject2059.appspot.com',
    iosBundleId: 'com.example.reserveVol.RunnerTests',
  );
}
